### ISSUE TITLE
ESP32S3 firmware

### ISSUE THREAD

**Issue by manupawickramasinghe** [martin-ger/esp32_nat_router#114]
I build the firmware for ESP32S3 , how can I upload these files to this repo?

**Comment by sfranzyshen** [comment]
try forking this repository ... making the changes (add files) ... then make a pull request.
even if the maintainer doesn't accept your request ... others who are interested could still 
be avle to find the files ...
~peace

**Comment by manupawickramasinghe** [comment]
Thank you
