### ISSUE TITLE
Missing an status-indicating GPIO-LED

### ISSUE THREAD

**Issue by CRprog** [martin-ger/esp32_nat_router#12]
At first I've tested your ESP8266-nat-router, it works ... But unfortunately it was much too slow for my Smart TV. Also the connection to AP (Fritzbox) after Powerup/Reset did not always work. (I admit: The signal strength is low at RSSI: -80)
With the ESP32-software here it works now much more reliably and fast enough at exact the same position and orientation of the ESP-Antenna.
What I'am missing compared to the ESP8266-Version is a LED-Output (maybe GPIO2) to indicate
"No AP connect"/"AP connect"/"AP connect with traffic".
Maybe you will find some time to integrate that later.
Regards.

**Comment by on2aav** [comment]
Same here, all works greatly, just missing the GPIO2 Led when connected, or when activity.

**Comment by CRprog** [comment]
Thank you for adding the Status-LED-feature last month, but I haven't tested it yet.
Nevertheless, I think I can close this issue now.
