### ISSUE TITLE
static IPs > x.x.x.128/24?

### ISSUE THREAD

**Issue by mahesh2000** [martin-ger/esp32_nat_router#2]
hi, does your statement about the ESP8266 about static IPs hold for the ESP32 port as well, that x.x.x.129 to .255 are available for static IP addresses?

"The ESP's DHCP server uses addresses from x.x.x.2/24 to x.x.x.128/24. Any higher IP address can be assigned statically without any risc of being reassigned dynamically by DHCP."

**Comment by martin-ger** [comment]
The DHCP server assigns at max 64 addresses (default 8), see menuconfig components->lwip->dhcps. So anything beyond x.x.x.128 should be save.

**Comment by mahesh2000** [comment]
thank you!
