### ISSUE TITLE
can it change MAC address

### ISSUE THREAD

**Issue by iansun2** [martin-ger/esp32_nat_router#3]
can it change MAC address like [https://github.com/martin-ger/esp_wifi_repeater](url) 
using " set [ap_mac|sta_mac] xx:xx:xx:xx:xx:xx " command

**Comment by martin-ger** [comment]
No, not yet, however should not be hard to add, if required using [esp_wifi_set_mac()](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_wifi.html#_CPPv416esp_wifi_set_mac16wifi_interface_tAL6E_K7uint8_t).

**Comment by iansun2** [comment]
> No, not yet, however should not be hard to add, if required using [esp_wifi_set_mac()](https://docs.espressif.com/projects/esp-idf/en/latest/api-reference/network/esp_wifi.html#_CPPv416esp_wifi_set_mac16wifi_interface_tAL6E_K7uint8_t).
I cannot install esp-idf .....
I have try on windows10 and ubuntu
But I always get error 1 or 2 depend on python 2 or 3

**Comment by martin-ger** [comment]
Sorry, for me on Ubuntu 18 it worked as described. Please ask in the esp-idf repository.
