### ISSUE TITLE
No file build\partitions_example.bin

### ISSUE THREAD

**Issue by fscii** [martin-ger/esp32_nat_router#47]
In trying to flash using esptool.py there's no \build\partitions_example.bin

from Readme.md

esptool.py --chip esp32 --port /dev/ttyUSB0 \
--baud 115200 --before default_reset --after hard_reset write_flash \
-z --flash_mode dio --flash_freq 40m --flash_size detect \
0x1000 build/bootloader/bootloader.bin \
0x10000 build/esp32_nat_router.bin \
0x8000 build/partitions_example.bin

**Comment by martin-ger** [comment]
Thanks for the hint - added it.
