### ISSUE TITLE
Portmap

### ISSUE THREAD

**Issue by JoergSH** [martin-ger/esp32_nat_router#52]
I don't understand what I have to send via terminal. I have a device where I connected with 192.168.4.1 and need to map to port 2000. Could you please help me. Thanks a lot

**Comment by martin-ger** [comment]
`portmap add TCP 2000 192.168.4.1 2000`
this makes port 2000 accessible at the uplink IP address of the ESP.

**Comment by JoergSH** [comment]
Thx a lot
