### ISSUE TITLE
HOW TO COMPILE FROM SCRATCH

### ISSUE THREAD

**Issue by morpheuslord** [martin-ger/esp32_nat_router#83]
Hello there,
i wanted to update the web interface so i wanted to compile from scratch how can i do that.

thank you

**Comment by martin-ger** [comment]
https://github.com/martin-ger/esp32_nat_router#building-the-binaries

Am 17. April 2022 11:22:11 schrieb morpheuslord ***@***.***>:

**Comment by morpheuslord** [comment]
Yes it worked
